<a href="https://colab.research.google.com/github/PhatDiaz/ai-engineer-roadmap/blob/main/day10_pandas_groupby_merge_apply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1 — value_counts()**

In [ ]:
# Dataset
import pandas as pd

data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy"],

    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", "HCM"],

    "Score": [8.5, 7.0, 9.0, 6.0, 8.0, 7.5]
}

df = pd.DataFrame(data)

# Muốn biết mỗi thành phố có bao nhiêu student:
print(df["City"].value_counts())

#  value_counts()
#       ↓
# đếm frequency của từng giá trị unique

City
Hanoi     3
HCM       2
Danang    1
Name: count, dtype: int64

**value_counts(normalize=True)**

In [ ]:
# Optional nhưng nên biết:
print(df["City"].value_counts(normalize=True))

# -> Tỷ lệ thay vì số lượng

City
Hanoi     0.500000
HCM       0.333333
Danang    0.166667
Name: proportion, dtype: float64

**unique() và nunique()**

In [ ]:
# Để hỗ trợ hiểu value_counts():
print(df["City"].unique())
# -> Các giá trị khác nhau

# Còn:
print(df["City"].nunique())
# -> Số lượng giá trị unique

['Hanoi' 'HCM' 'Danang']
3

***NHỚ***
```
unique()
→ các giá trị unique là gì?

nunique()
→ có bao nhiêu giá trị unique?

value_counts()
→ mỗi giá trị xuất hiện bao nhiêu lần?
```

# **Task 2 — groupby()**

In [ ]:
# Dataset
data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy"],

    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", "HCM" ],

    "Score": [8.5, 7.0, 9.0, 6.0, 8.0, 7.5]
}

df = pd.DataFrame(data)

# Muốn tính average Score theo City:
print(df.groupby("City")["Score"].mean())

City
Danang    6.00
HCM       7.25
Hanoi     8.50
Name: Score, dtype: float64

**Hiểu groupby()**

Tư duy:
```
Dataset
   ↓
chia thành các group theo City

Hanoi
→ An
→ Cuong
→ Hoa

HCM
→ Binh
→ Huy

Danang
→ Dung
```

Sau đó:
```
mỗi group
   ↓
mean()
```

Tóm lại:
```
Split
↓
Apply
↓
Combine
```

**Group theo một column**

`df.groupby("City")["Score"].mean()`

Phân tích:
```
df.groupby("City")
→ nhóm rows theo City

["Score"]
→ chỉ lấy Score

.mean()
→ tính mean từng group
```

In [ ]:
# Các aggregation phổ biến

print(df.groupby("City")["Score"].mean())
print(df.groupby("City")["Score"].sum())
print(df.groupby("City")["Score"].min())
print(df.groupby("City")["Score"].max())
print(df.groupby("City")["Score"].count())

City
Danang    6.00
HCM       7.25
Hanoi     8.50
Name: Score, dtype: float64
City
Danang     6.0
HCM       14.5
Hanoi     25.5
Name: Score, dtype: float64
City
Danang    6.0
HCM       7.0
Hanoi     8.0
Name: Score, dtype: float64
City
Danang    6.0
HCM       7.5
Hanoi     9.0
Name: Score, dtype: float64
City
Danang    1
HCM       2
Hanoi     3
Name: Score, dtype: int64

**Group nhiều numerical columns**

In [ ]:
# Dataset
data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy"],

    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", "HCM" ],

    "Math": [8.5, 6.0, 9.0, 5.5, 7.5, 8.0],

    "AI": [9.0, 7.5, 8.5, 7.0, 8.0, 9.5]
}

df = pd.DataFrame(data)

# Tính average Math và AI theo City:
print(df.groupby("City")[["Math", "AI"]].mean())

            Math   AI
City
Danang  5.500000  7.0
HCM     7.000000  8.5
Hanoi   8.333333  8.5

**Group theo nhiều columns**

In [ ]:
# Dataset
data = {
    "City": ["Hanoi", "Hanoi", "HCM", "HCM"],

    "Gender": ["Male", "Female", "Male", "Female"],

    "Score": [8, 9, 7, 8]
}

df = pd.DataFrame(data)

print(df.groupby(["City", "Gender"])["Score"].mean())

City   Gender
HCM    Female    8.0
       Male      7.0
Hanoi  Female    9.0
       Male      8.0
Name: Score, dtype: float64

# **Task 3 — .agg()**

In [ ]:
# Muốn một lúc tính nhiều statistics:
print(df.groupby("City")["Score"].agg([
    "mean",
    "min",
    "max"
]))

       mean  min  max
City
HCM     7.5    7    8
Hanoi   8.5    8    9

**agg() với dictionary**

In [ ]:
# print(df.groupby("City").agg({
#     "Math": "mean",
#     "AI": "max"
# }))

# Nghĩa là:
# Math
# → lấy mean theo City

# AI
# → lấy max theo City

**reset_index()**

In [ ]:
# Sau:
result = (df.groupby("City")["Score"].mean())

# City thường trở thành index

# Nếu muốn trở lại DataFrame bình thường:
result = (
    df.groupby("City")["Score"]
    .mean()
    .reset_index()
)

# Khi đó: City trở thành column trở lại.

# **Task 4 — apply()**

apply() cho phép áp dụng một function lên Series hoặc DataFrame

In [ ]:
# Ví dụ:
scores = pd.Series([8.5 ,7.0, 9.0, 6.0])

def classify_score(score):
  if score >= 8.5:
    return "Excellent"
  elif score >= 7:
    return "Good"
  elif score >= 5:
    return "Average"
  else:
    return "Fail"

print(scores.apply(classify_score))

0    Excellent
1         Good
2    Excellent
3      Average
dtype: object

**apply() với DataFrame column**

```
df["Grade"] = df["Score"].apply(
    classify_score
)
```
Bây giờ:
```
Name    Score    Grade
An      8.5      Excellent
Binh    7.0      Good
...
```
Đây là pattern rất phổ biến:
```
existing column
      ↓
apply(function)
      ↓
new column
```

**apply() + lambda**

Nếu function đơn giản:
```
df["Passed"] = df["Score"].apply(
    lambda score: score >= 5
)
```
Output:
```
True
True
True
...
```

**Khi nào dùng apply()?**

Ví dụ cần logic:
```
def classify_score(score):
    ...
```
thì:

```
df["Score"].apply(
    classify_score
)
```
rất dễ đọc

Nhưng nếu chỉ muốn:

`Score * 2`

đừng viết:
```
df["Score"].apply(
    lambda x: x * 2
)
```

Ưu tiên:
```
df["Score"] * 2
```

# **Task 5 — merge()**

Trong thực tế dữ liệu có thể nằm ở nhiều bảng

In [ ]:
# Ví dụ bảng students

students = pd.DataFrame({
    "StudentID": [101, 102, 103],
    "Name": ["An", "Binh", "Cuong"]
})

# Bảng Scores
scores = pd.DataFrame({
    "StudentID": [101, 102, 103],
    "Score": [8.5, 7.0, 9.0]
})

# Muốn ghép:
merge_df = pd.merge(students, scores, on="StudentID")
print(merge_df)

   StudentID   Name  Score
0        101     An    8.5
1        102   Binh    7.0
2        103  Cuong    9.0

**Hiểu on**

```
on="StudentID"
```
nghĩa là:

`Dùng StudentID làm key để ghép hai DataFrame`

Tư duy rất giống database join
```
students
StudentID
    ↓
match
    ↑
StudentID
scores
```

**inner merge**

In [ ]:
# Giả sử
students = pd.DataFrame({
    "StudentID": [101, 102, 103],
    "Name": ["An", "Binh", "Cuong"]
})

scores = pd.DataFrame({
    "StudentID": [101, 102, 104],
    "Score": [8.5, 7.0, 9.0]
})

# Nếu
pd.merge(students, scores, on="StudentID", how="inner")

# Chỉ giữ ID xuất hiện ở cả 2 bảng: 101, 102

   StudentID  Name  Score
0        101    An    8.5
1        102  Binh    7.0

**left merge**

In [ ]:
pd.merge(students, scores, on="StudentID", how="left")

# Chỉ giữ ID xuất hiện ở bảng students (giữ tất cả rows của bảng bên trái)

   StudentID   Name  Score
0        101     An    8.5
1        102   Binh    7.0
2        103  Cuong    NaN

**Tóm tắt:**

```
inner
→ chỉ phần match

left
→ giữ tất cả bên trái

right
→ giữ tất cả bên phải

outer
→ giữ tất cả hai bên
```

# **Coding Practice — 15 bài**

In [ ]:
# Dùng dataset

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104, 105, 106],
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy"],
    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", "HCM"],
    "Math": [8.5, 6.0, 9.0, 5.5, 7.5, 8.0],
    "AI": [9.0, 7.5, 8.5, 7.0, 8.0, 9.5]
})

# Ex 1: value_counts()
print(students["City"].value_counts())

# Ex 2: Unique City
print(students["City"].unique())
print(students["City"].nunique())

# Ex 3: Group Mean
print(students.groupby("City")["Math"].mean())

# Ex 4: Group AI
print(students.groupby("City")["AI"].mean())

# Ex 5: Multiple Columns
print(students.groupby("City")[["Math", "AI"]].mean())

# Ex 6: Multiple Aggregations
print(students.groupby("City")["Math"].agg(["mean", "min", "max"]))

# Ex 7: Count per group
print(students.groupby("City")["Name"].count())

# Ex 8: Apply Classifications
def classify_ai(score):
  if score >= 9:
    return "Excellent"
  elif score >= 8:
    return "Good"
  elif score >= 7:
    return "Average"
  else:
    return "Fail"

students["AI_Level"] = students["AI"].apply(classify_ai)
print(students)

# Ex 9: Apply Lambda
students["Passed_AI"] = students["AI"].apply(lambda score: score >= 7)
print(students)

# Ex 10: Average Column
students["Average"] = (students["Math"] + students["AI"]) / 2
print(students)

City
Hanoi     3
HCM       2
Danang    1
Name: count, dtype: int64
['Hanoi' 'HCM' 'Danang']
3
City
Danang    5.500000
HCM       7.000000
Hanoi     8.333333
Name: Math, dtype: float64
City
Danang    7.0
HCM       8.5
Hanoi     8.5
Name: AI, dtype: float64
            Math   AI
City
Danang  5.500000  7.0
HCM     7.000000  8.5
Hanoi   8.333333  8.5
            mean  min  max
City
Danang  5.500000  5.5  5.5
HCM     7.000000  6.0  8.0
Hanoi   8.333333  7.5  9.0
City
Danang    1
HCM       2
Hanoi     3
Name: Name, dtype: int64
   StudentID   Name    City  Math   AI   AI_Level
0        101     An   Hanoi   8.5  9.0  Excellent
1        102   Binh     HCM   6.0  7.5    Average
2        103  Cuong   Hanoi   9.0  8.5       Good
3        104   Dung  Danang   5.5  7.0    Average
4        105    Hoa   Hanoi   7.5  8.0       Good
5        106    Huy     HCM   8.0  9.5  Excellent
   StudentID   Name    City  Math   AI   AI_Level  Passed_AI
0        101     An   Hanoi   8.5  9.0  Excellent       True
1        102   Binh     HCM   6.0  7.5    Average       True
2        103  Cuong   Hanoi   9.0  8.5       Good       True
3        104   Dung  Danang   5.5  7.0    Average       True
4        105    Hoa   Hanoi   7.5  8.0       Good       True
5        106    Huy     HCM   8.0  9.5  Excellent       True
   StudentID   Name    City  Math   AI   AI_Level  Passed_AI  Average
0        101     An   Hanoi   8.5  9.0  Excellent       True     8.75
1        102   Binh     HCM   6.0  7.5    Average       True     6.75
2        103  Cuong   Hanoi   9.0  8.5       Good       True     8.75
3        104   Dung  Danang   5.5  7.0    Average       True     6.25
4        105    Hoa   Hanoi   7.5  8.0       Good       True     7.75
5        106    Huy     HCM   8.0  9.5  Excellent       True     8.75

**Merge Exercises**

In [ ]:
courses = pd.DataFrame({
    "StudentID": [101, 102, 103, 107],
    "Course": ["AI", "Data Science", "AI", "Machine learning"]
})

# Ex 11: Inner merge
print("------------Inner------------")
inner_merge_df = pd.merge(students, courses, on="StudentID", how="inner")
print(inner_merge_df)
print("\n")

# Ex 12: Left merge
print("------------Left------------")
print(pd.merge(students, courses, on="StudentID", how="left"))
print("\n")

# Ex 13: Outer merge
print("------------Outer------------")
print(pd.merge(students, courses, on="StudentID", how="outer"))
print("\n")

# Ex 14: Group after Merge
print(inner_merge_df.groupby("Course")["AI"].mean())

------------Inner------------
   StudentID   Name   City  Math   AI   AI_Level  Passed_AI  Average  \
0        101     An  Hanoi   8.5  9.0  Excellent       True     8.75
1        102   Binh    HCM   6.0  7.5    Average       True     6.75
2        103  Cuong  Hanoi   9.0  8.5       Good       True     8.75

         Course
0            AI
1  Data Science
2            AI


------------Left------------
   StudentID   Name    City  Math   AI   AI_Level  Passed_AI  Average  \
0        101     An   Hanoi   8.5  9.0  Excellent       True     8.75
1        102   Binh     HCM   6.0  7.5    Average       True     6.75
2        103  Cuong   Hanoi   9.0  8.5       Good       True     8.75
3        104   Dung  Danang   5.5  7.0    Average       True     6.25
4        105    Hoa   Hanoi   7.5  8.0       Good       True     7.75
5        106    Huy     HCM   8.0  9.5  Excellent       True     8.75

         Course
0            AI
1  Data Science
2            AI
3           NaN
4           NaN
5           NaN


------------Outer------------
   StudentID   Name    City  Math   AI   AI_Level Passed_AI  Average  \
0        101     An   Hanoi   8.5  9.0  Excellent      True     8.75
1        102   Binh     HCM   6.0  7.5    Average      True     6.75
2        103  Cuong   Hanoi   9.0  8.5       Good      True     8.75
3        104   Dung  Danang   5.5  7.0    Average      True     6.25
4        105    Hoa   Hanoi   7.5  8.0       Good      True     7.75
5        106    Huy     HCM   8.0  9.5  Excellent      True     8.75
6        107    NaN     NaN   NaN  NaN        NaN       NaN      NaN

             Course
0                AI
1      Data Science
2                AI
3               NaN
4               NaN
5               NaN
6  Machine learning


Course
AI              8.75
Data Science    7.50
Name: AI, dtype: float64

In [ ]:
# Ex 15: Combined Task
students["Average"] = (students["Math"] + students["AI"]) / 2

def classify_student(average):
    if average >= 8.5:
        return "Excellent"
    elif average >= 7:
        return "Good"
    elif average >= 5:
        return "Average"
    else:
        return "Fail"

students["Level"] = students["Average"].apply(classify_student)

city_average = students.groupby("City")["Average"].mean()

city_average = city_average.sort_values(ascending=False)

print(students)
print(city_average)

   StudentID   Name    City  Math   AI   AI_Level  Passed_AI  Average  \
0        101     An   Hanoi   8.5  9.0  Excellent       True     8.75
1        102   Binh     HCM   6.0  7.5    Average       True     6.75
2        103  Cuong   Hanoi   9.0  8.5       Good       True     8.75
3        104   Dung  Danang   5.5  7.0    Average       True     6.25
4        105    Hoa   Hanoi   7.5  8.0       Good       True     7.75
5        106    Huy     HCM   8.0  9.5  Excellent       True     8.75

       Level
0  Excellent
1    Average
2  Excellent
3    Average
4       Good
5  Excellent
City
Hanoi     8.416667
HCM       7.750000
Danang    6.250000
Name: Average, dtype: float64

# **Task 7 — Mini Challenge**

In [79]:
students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104, 105, 106],
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy"],
    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", "HCM"],
})

scores = pd.DataFrame({
    "StudentID": [101, 102, 103, 104, 105, 106],
    "Math": [8.5, 6.0, 9.0, 5.5, 7.5, 8.0],
    "English": [7.0, 8.0, 9.5, 6.0, 8.5, 7.5],
    "AI": [9.0, 7.5, 8.5, 7.0, 8.0, 9.5]
})

# Require 1: Merge
df = pd.merge(students, scores, on="StudentID")
print(df)

# Require 2: Overview
# print(df.head())

# print(df.shape)

# df.info()

# Require 3: City Count
print(df["City"].value_counts())

# Require 4: Average Score
df["Average"] = (df['AI'] + df['Math'] + df['English']) / 3
print(df)

# Require 5: Classification
def classify_student(average):
  if average >= 8.5:
    return "Excellent"
  elif average >= 7:
    return "Good"
  elif average >= 5:
    return "Average"
  else:
    return "Fail"

df["Level"] = df["Average"].apply(classify_student)
# print(df)

# Require 6: Passed
df["Passed"] = df["Average"].apply(lambda x: x >= 5)
print(df)

# Require 7: Average by City
print(df.groupby("City")["Average"].mean())

# Require 8: Subject Average by City
print(df.groupby("City")[["Math", "English", "AI"]].mean())

# Require 9: City Statistics
print(df.groupby("City")["Average"].agg(["mean", "min", "max"]))

# Require 10: Level Count
print(df["Level"].value_counts())

# Require 11: Best City
city_average = df.groupby("City")["Average"].mean()

best_city = city_average.idxmax()
print(best_city)

# Require 12: Best Student per City
max_average = df.groupby("City")["Average"].max()

for city, average in max_average.items():
    best_student = df[(df["City"] == city) & (df["Average"] == average)]

    print(best_student[["City", "Name", "Average"]])

# Require 13: Sort Students
print(df.sort_values(by="Average", ascending=False)[["Name", "City", "Average", "Level"]])

# Require 14: Summary DataFrame
city_summary = df.groupby("City").agg(
    AverageScore = ("Average", "mean"),
    StudentCount = ("StudentID", "count")
).reset_index()

# Require 15: Save Result
city_summary.to_csv("student_performance_summary.csv", index=False)

   StudentID   Name    City  Math  English   AI
0        101     An   Hanoi   8.5      7.0  9.0
1        102   Binh     HCM   6.0      8.0  7.5
2        103  Cuong   Hanoi   9.0      9.5  8.5
3        104   Dung  Danang   5.5      6.0  7.0
4        105    Hoa   Hanoi   7.5      8.5  8.0
5        106    Huy     HCM   8.0      7.5  9.5
City
Hanoi     3
HCM       2
Danang    1
Name: count, dtype: int64
   StudentID   Name    City  Math  English   AI   Average
0        101     An   Hanoi   8.5      7.0  9.0  8.166667
1        102   Binh     HCM   6.0      8.0  7.5  7.166667
2        103  Cuong   Hanoi   9.0      9.5  8.5  9.000000
3        104   Dung  Danang   5.5      6.0  7.0  6.166667
4        105    Hoa   Hanoi   7.5      8.5  8.0  8.000000
5        106    Huy     HCM   8.0      7.5  9.5  8.333333
   StudentID   Name    City  Math  English   AI   Average      Level  Passed
0        101     An   Hanoi   8.5      7.0  9.0  8.166667       Good    True
1        102   Binh     HCM   6.0      8.0  7.5  7.166667       Good    True
2        103  Cuong   Hanoi   9.0      9.5  8.5  9.000000  Excellent    True
3        104   Dung  Danang   5.5      6.0  7.0  6.166667    Average    True
4        105    Hoa   Hanoi   7.5      8.5  8.0  8.000000       Good    True
5        106    Huy     HCM   8.0      7.5  9.5  8.333333       Good    True
City
Danang    6.166667
HCM       7.750000
Hanoi     8.388889
Name: Average, dtype: float64
            Math   English   AI
City
Danang  5.500000  6.000000  7.0
HCM     7.000000  7.750000  8.5
Hanoi   8.333333  8.333333  8.5
            mean       min       max
City
Danang  6.166667  6.166667  6.166667
HCM     7.750000  7.166667  8.333333
Hanoi   8.388889  8.000000  9.000000
Level
Good         4
Excellent    1
Average      1
Name: count, dtype: int64
Hanoi
     City  Name   Average
3  Danang  Dung  6.166667
  City Name   Average
5  HCM  Huy  8.333333
    City   Name  Average
2  Hanoi  Cuong      9.0
    Name    City   Average      Level
2  Cuong   Hanoi  9.000000  Excellent
5    Huy     HCM  8.333333       Good
0     An   Hanoi  8.166667       Good
4    Hoa   Hanoi  8.000000       Good
1   Binh     HCM  7.166667       Good
3   Dung  Danang  6.166667    Average