<a href="https://colab.research.google.com/github/PhatDiaz/ai-engineer-roadmap/blob/main/day08_pandas_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1 — Pandas là gì?**

In [73]:
# Import
import pandas as pd
import numpy as np

**NumPy Array**

```
scores = np.array([
    [8.5, 7.0, 9.0],
    [6.0, 8.0, 7.5]
])
```

Dữ liệu:
```
[[8.5 7.0 9.0]
 [6.0 8.0 7.5]]
```

Bạn phải tự nhớ:
```
column 0 = Math
column 1 = English
column 2 = AI
```

**Pandas DataFrame**

In [74]:
data = {
    "Math": [8.5, 6.0],
    "English": [7.0, 8.0],
    "AI": [9.0, 7.5]
}

df = pd.DataFrame(data)

print(df)

   Math  English   AI
0   8.5      7.0  9.0
1   6.0      8.0  7.5

Pandas có column names nên dễ làm việc với dataset thực tế hơn

# **Task 2 — Series**

Series có thể hiểu là một cột dữ liệu 1 chiều

In [75]:
# Ví dụ
scores = pd.Series([8.5, 7.0, 9.0, 6.0])

print(scores)

0    8.5
1    7.0
2    9.0
3    6.0
dtype: float64

**Series có index riêng**

In [76]:
scores = pd.Series(
    [8.5, 7.0, 9.0],
    index=["An", "Binh", 'Cuong']
)

print(scores)

print(scores['An'])

An       8.5
Binh     7.0
Cuong    9.0
dtype: float64
8.5

**Một số thuộc tính Series**

```
print(scores.shape)
print(scores.size)
print(scores.dtype)
print(scores.index)
print(scores.values)
```

**Series vs NumPy Array**

In [77]:
# NumPy
arr = np.array([8.5, 7.0, 9.0])

# Pandas
series = pd.Series([8.5, 7.0, 9.0])

**Điểm khác nổi bật:**

**NumPy Array**
→ chủ yếu dựa trên position

**Pandas Series**
→ có index/label

# **Task 3 — DataFrame**

**DataFrame = bảng gồm nhiều rows và columns**

In [78]:
# Ví dụ
students = {
    "Name": ["An", "Binh", "Cuong", "Dung"],
    "Age": [22, 25, 21, 23],
    "Score": [8.5, 7.0, 9.0, 6.0]
}

df = pd.DataFrame(students)
print(df)

    Name  Age  Score
0     An   22    8.5
1   Binh   25    7.0
2  Cuong   21    9.0
3   Dung   23    6.0

**Hiểu cấu trúc DataFrame**

```
       columns
          ↓
     Name Age Score
0     An   22  8.5
1   Binh   25  7.0
2  Cuong   21  9.0
↑
index
```
DataFrame có:

```
rows
columns
index
values
data types
```

**df.shape**

```
print(df.shape)
```
→ (4, 3)

Nghĩa là:

```
4 rows
3 columns
```

**df.columns**

```
print(df.columns)
```
→ đại loại:

```
Index(['Name', 'Age', 'Score'], dtype='object')
```

**df.index**

```
print(df.index)
```
→

```
RangeIndex(start=0, stop=4, step=1)
```

**df.dtypes**

```
print(df.dtypes)
```
Có thể ra:

```
Name      object
Age        int64
Score    float64
```

Điểm rất quan trọng:

```
NumPy array
→ thường có một dtype chung

Pandas DataFrame
→ mỗi column có thể có dtype riêng
```

Ví dụ:
```
Name  → string/object
Age   → int
Score → float
```

**Lấy một column**

```
print(df["Name"])
```

Kết quả là Series:

```
0       An
1     Binh
2    Cuong
3     Dung
```

**Lấy nhiều columns**

```
print(
    df[
        ["Name", "Score"]
    ]
)
```
Kết quả là DataFrame:

```
    Name  Score
0     An    8.5
1   Binh    7.0
2  Cuong    9.0
3   Dung    6.0
```
Đây là điểm dễ nhầm:

`df["Score"]`

**→ Series**

nhưng:

`df[["Score"]]`


**→ DataFrame**

# **Task 4 — Đọc CSV**

**Tạo một CSV nhỏ để luyện**

In [79]:
import pandas as pd

data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa"],
    "Age": [22, 25, 21, 23, 24],
    "Score": [8.5, 7.0, 9.0, 6.0, 8.0],
    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi"]
}

df = pd.DataFrame(data)

df.to_csv("students.csv", index=False)

# Lệnh index = False có nghĩa:
# Không ghi column index 0,1,2,... của Pandas vào CSV.

**Đọc CSV**

In [80]:
df = pd.read_csv("students.csv")

print(df)

    Name  Age  Score    City
0     An   22    8.5   Hanoi
1   Binh   25    7.0     HCM
2  Cuong   21    9.0   Hanoi
3   Dung   23    6.0  Danang
4    Hoa   24    8.0   Hanoi

# **Task 5 — Khám phá Dataset**

Đây là phần cực kỳ quan trọng trong AI/ML.

Khi nhận một dataset mới, **đừng bắt đầu train model ngay**.

Việc đầu tiên thường là hiểu dữ liệu.

Một workflow đơn giản:

```
Load Dataset
     ↓
head()
     ↓
shape
     ↓
columns
     ↓
dtypes
     ↓
info()
     ↓
describe()
```

**head()**

`df.head()`

Mặc định:

`5 rows đầu`

Nếu:

`df.head(3)`

→ 3 rows đầu

**tail()**

Mặc dù không phải trọng tâm roadmap hôm nay, bạn nên biết:

`df.tail()`

→ 5 rows cuối

**shape**

`df.shape`

Ví dụ:
`(5, 4)`

→
5 rows, 4 columns

**columns**

`df.columns`

→ tên các columns.

**dtypes**

`df.dtypes`

→ dtype của từng column

**info()**

`df.info()`

Đây là function rất quan trọng.

Nó cho ta biết:

```
số rows
columns
non-null count
dtype
memory
```
Ví dụ:

```
Name        5 non-null        object
Age         5 non-null        int64
Score       5 non-null        float64
City        5 non-null        object
```

Sau này khi dataset có missing values:


```
1000 rows

Age
950 non-null
```
bạn sẽ phát hiện:

`50 missing values`

**describe()**

`df.describe()`

Thường áp dụng cho numerical columns

**Ví dụ:**
```
            Age      Score

count       5.0       5.0
mean        ...
std         ...
min         ...
25%         ...
50%         ...
75%         ...
max         ...
```
Ta đã học: **mean, std, min, max** ở NumPy

Bây giờ Pandas tổng hợp chúng cho từng numerical column

**25%, 50%, 75% là gì?**

Chúng là **quartiles** (tứ phân vị)

Chỉ cần biết là:

```
25% → Q1
50% → median
75% → Q3
```

**Một workflow bạn nên tập thành thói quen**

In [87]:
# Khi load dataset
# df = pd.read_csv("data.csv")

# # thì có thể kiểm tra:
print(df.head())

print(df.shape)

print(df.columns)

print(df.dtypes)

df.info()

print(df.describe())

# # Sau này gần như mỗi project ML đều bắt đầu kiểu này

    Name  Age  Math  English   AI    City   Average
0     An   22   8.5      7.0  9.0   Hanoi  8.166667
1   Binh   25   6.0      8.0  7.5     HCM  7.166667
2  Cuong   21   9.0      9.5  8.5   Hanoi  9.000000
3   Dung   23   5.5      6.0  7.0  Danang  6.166667
4    Hoa   24   7.5      8.5  8.0   Hanoi  8.000000
(6, 7)
Index(['Name', 'Age', 'Math', 'English', 'AI', 'City', 'Average'], dtype='object')
Name        object
Age          int64
Math       float64
English    float64
AI         float64
City        object
Average    float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int64
 2   Math     6 non-null      float64
 3   English  6 non-null      float64
 4   AI       6 non-null      float64
 5   City     6 non-null      object
 6   Average  6 non-null      float64
dtypes: float64(4), int64(1), object(2)
memory usage: 468.0+ bytes
             Age      Math   English        AI   Average
count   6.000000  6.000000  6.000000  6.000000  6.000000
mean   23.500000  7.416667  7.750000  8.250000  7.805556
std     1.870829  1.393437  1.214496  0.935414  0.996754
min    21.000000  5.500000  6.000000  7.000000  6.166667
25%    22.250000  6.375000  7.125000  7.625000  7.375000
50%    23.500000  7.750000  7.750000  8.250000  8.083333
75%    24.750000  8.375000  8.375000  8.875000  8.291667
max    26.000000  9.000000  9.500000  9.500000  9.000000

# **Task 6 — Coding Practice**

In [82]:
# Ex 1: Series

data = pd.Series([8.5, 7.0, 9.0, 6.0])

print(data)

print(data.shape)

print(data.size)

print(data.dtype)

0    8.5
1    7.0
2    9.0
3    6.0
dtype: float64
(4,)
4
float64

In [83]:
# Ex 2: Custom index

scores = pd.Series([8.5, 7.0, 9.0, 6.0], index=["An", "Binh", "Cuong", "Dung"])

print(scores["Cuong"])

9.0

In [88]:
# Ex 3: DataFrame

data = {
    "Name": ["An", "Binh", "Cuong", "Dung"],
    "Age": [22, 25, 21, 23],
    "Score": [8.5, 7.0, 9.0, 6.0]
}

scores = pd.DataFrame(data)

print(scores)

# Ex 4
print(scores.shape)

print(scores.columns)

print(scores.index)

print(scores.dtypes)

# Ex 5
print(scores["Score"])
print(type(scores["Score"]))

# Ex 6
print(scores[["Name", "Score"]])
print(type(scores[["Name", "Score"]]))

# Ex 7
scores.to_csv("students.csv", index=False)

# Ex 8
print(pd.read_csv("students.csv"))

# Ex 9
print(scores.head(3))

# Ex 10
print(scores.tail(2))

# Ex 11
print(scores.info())
# Bài 11 print ra
# - Có 4 rows
# - Có 3 columns
# - column age là int
# - column score là float

# Ex 12
print(scores.describe())
# mean của Age là 22.750000
# mean của Score là 7.625000
# min Score là 6.000000
# max Score là 9.000000

# Ex 13
print(scores["Score"].mean())

# Ex 14
print(scores["Score"].max())

    Name  Age  Score
0     An   22    8.5
1   Binh   25    7.0
2  Cuong   21    9.0
3   Dung   23    6.0
(4, 3)
Index(['Name', 'Age', 'Score'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
Name      object
Age        int64
Score    float64
dtype: object
0    8.5
1    7.0
2    9.0
3    6.0
Name: Score, dtype: float64
<class 'pandas.core.series.Series'>
    Name  Score
0     An    8.5
1   Binh    7.0
2  Cuong    9.0
3   Dung    6.0
<class 'pandas.core.frame.DataFrame'>
    Name  Age  Score
0     An   22    8.5
1   Binh   25    7.0
2  Cuong   21    9.0
3   Dung   23    6.0
    Name  Age  Score
0     An   22    8.5
1   Binh   25    7.0
2  Cuong   21    9.0
    Name  Age  Score
2  Cuong   21    9.0
3   Dung   23    6.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes
None
             Age     Score
count   4.000000  4.000000
mean   22.750000  7.625000
std     1.707825  1.376893
min    21.000000  6.000000
25%    21.750000  6.750000
50%    22.500000  7.750000
75%    23.500000  8.625000
max    25.000000  9.000000
7.625
9.0

In [90]:
# Ex 15

scores_numpy = np.array([8.5, 7.0, 9.0, 6.0])

scores_pandas = pd.Series([8.5, 7.0, 9.0, 6.0])

print(np.mean(scores_numpy))
print(scores_pandas.mean())

# Kết quả mean giống nhau vì cùng dữ liệu. NumPy array chủ yếu làm việc dựa trên vị trí và mạnh về numerical computation,
# còn Pandas Series có index/label nên thuận tiện hơn khi xử lý dữ liệu dạng bảng.

7.625
7.625

# **Task 7 — Mini Challenge**

In [86]:
import pandas as pd

data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy"],
    "Age": [22, 25, 21, 23, 24, 26],
    "Math": [8.5, 6.0, 9.0, 5.5, 7.5, 8.0],
    "English": [7.0, 8.0, 9.5, 6.0, 8.5, 7.5],
    "AI": [9.0, 7.5, 8.5, 7.0, 8.0, 9.5],
    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", "HCM"]
}

df = pd.DataFrame(data)

# Require 1: Overview
display(df)

print(df.shape)

print(df.columns)

print(df.dtypes)

# Require 2: First Rows
display(df.head(3))

# Require 3: Dataset Information
print(df.info())

# Có 6 rows, 6 columns và không có missing value

# Require 4: Statistics
print(df.describe())

# Average Age: 23.500000
# Average Math: 7.416667
# Average English: 7.750000
# Average AI: 8.250000

# Require 5: Select Column
print(df["Name"])
# -> Kết quả là Series vì là cột dữ liệu 1 chiều

# Require 6: Select Multiple Columns
print(df[["Name", "Math", "AI"]])
# -> Kết quả là DataFrame

# Require 7: Subject Average
print(df[["Math", "English", "AI"]].mean())

# Require 8: Highest / Lowest
print(df[["Math", "AI"]].max())
print(df[["Math", "AI"]].min())

# Require 9: Save CSV
df.to_csv("student_dataset.csv", index=False)

# Require 10: Load CSV
loaded_df = pd.read_csv("student_dataset.csv")
loaded_df.head()

# Optional Challenge
df["Average"] = (df["Math"] + df["English"] + df["AI"]) / 3
df.head()

    Name  Age  Math  English   AI    City
0     An   22   8.5      7.0  9.0   Hanoi
1   Binh   25   6.0      8.0  7.5     HCM
2  Cuong   21   9.0      9.5  8.5   Hanoi
3   Dung   23   5.5      6.0  7.0  Danang
4    Hoa   24   7.5      8.5  8.0   Hanoi
5    Huy   26   8.0      7.5  9.5     HCM

(6, 6)
Index(['Name', 'Age', 'Math', 'English', 'AI', 'City'], dtype='object')
Name        object
Age          int64
Math       float64
English    float64
AI         float64
City        object
dtype: object

    Name  Age  Math  English   AI   City
0     An   22   8.5      7.0  9.0  Hanoi
1   Binh   25   6.0      8.0  7.5    HCM
2  Cuong   21   9.0      9.5  8.5  Hanoi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int64
 2   Math     6 non-null      float64
 3   English  6 non-null      float64
 4   AI       6 non-null      float64
 5   City     6 non-null      object
dtypes: float64(3), int64(1), object(2)
memory usage: 420.0+ bytes
None
             Age      Math   English        AI
count   6.000000  6.000000  6.000000  6.000000
mean   23.500000  7.416667  7.750000  8.250000
std     1.870829  1.393437  1.214496  0.935414
min    21.000000  5.500000  6.000000  7.000000
25%    22.250000  6.375000  7.125000  7.625000
50%    23.500000  7.750000  7.750000  8.250000
75%    24.750000  8.375000  8.375000  8.875000
max    26.000000  9.000000  9.500000  9.500000
0       An
1     Binh
2    Cuong
3     Dung
4      Hoa
5      Huy
Name: Name, dtype: object
    Name  Math   AI
0     An   8.5  9.0
1   Binh   6.0  7.5
2  Cuong   9.0  8.5
3   Dung   5.5  7.0
4    Hoa   7.5  8.0
5    Huy   8.0  9.5
Math       7.416667
English    7.750000
AI         8.250000
dtype: float64
Math    9.0
AI      9.5
dtype: float64
Math    5.5
AI      7.0
dtype: float64

    Name  Age  Math  English   AI    City   Average
0     An   22   8.5      7.0  9.0   Hanoi  8.166667
1   Binh   25   6.0      8.0  7.5     HCM  7.166667
2  Cuong   21   9.0      9.5  8.5   Hanoi  9.000000
3   Dung   23   5.5      6.0  7.0  Danang  6.166667
4    Hoa   24   7.5      8.5  8.0   Hanoi  8.000000

NumPy Array
```
→ n-dimensional numerical array
→ chủ yếu truy cập theo position
```

Pandas Series
```
→ dữ liệu 1 chiều
→ có index/label
```

Pandas DataFrame
```
→ dữ liệu bảng 2 chiều
→ rows + columns + labels
→ mỗi column có thể có dtype khác nhau
```