<a href="https://colab.research.google.com/github/PhatDiaz/ai-engineer-roadmap/blob/main/day09_pandas_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1 — Missing Values**

In [50]:
# Dataset
import pandas as pd
import numpy as np

data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa"],
    "Age": [22, 25, np.nan, 23, 24],
    "Score": [8.5, np.nan, 9.0, 6.0, 8.0],
    "City": ["Hanoi", "HCM", "Hanoi", None, "Hanoi"]
}

df = pd.DataFrame(data)

print(df)

    Name   Age  Score   City
0     An  22.0    8.5  Hanoi
1   Binh  25.0    NaN    HCM
2  Cuong   NaN    9.0  Hanoi
3   Dung  23.0    6.0   None
4    Hoa  24.0    8.0  Hanoi

**NaN là gì?**

NaN:
`Not a Number`

Trong Pandas, nó thường đại diện cho:
`missing value`

Ngoài np.nan, Pandas cũng có thể coi:
`None`

là missing value.

**isna()**

`df.isna()`

Sẽ trả về bảng boolean:
`False / True`

Ví dụ:

`print(df["Score"].isna())`

có thể ra:
```
0    False
1     True
2    False
3    False
4    False
```

**Đếm missing values**

Đây là pattern rất quan trọng
```
df.isna().sum()
```
Ví dụ:
```
Name     0
Age      1
Score    1
City     1
```
Tư duy:
```
isna()
↓
True / False
↓
sum()
↓
đếm True
```
Trong Python/ Pandas:
```
True  ≈ 1
False ≈ 0
```

**notna()**

Ngược với
```
isna()
```
là
```
notna()
```
Ví dụ:
```
df["Score"].notna()
```
→ những row có Score tồn tại

**Xóa missing values — dropna()**

```
clean_df = df.dropna()
```
Nó loại những row có missing value.

Ví dụ dataset trên chỉ giữ những row không thiếu dữ liệu.

**Không thay đổi DataFrame gốc nếu không gán lại**

```
df.dropna()
```
không có nghĩa là df đã thay đổi vĩnh viễn

Muốn lưu:
```
df = df.dropna()
```
hoặc:
```
clean_df = df.dropna()
```

**dropna(subset=...)**

Nếu chỉ quan tâm một column:
```
df.dropna(
    subset=["Score"]
)
```
Nghĩa là:

`Xóa những rows mà Score bị missing`

Các column khác có missing vẫn được giữ.

**Điền missing values — fillna()**

Ví dụ:
```
df["Score"] = df["Score"].fillna(0)
```
Missing Score sẽ thành 0.

Nhưng trong ML, điền 0 không phải lúc nào cũng hợp lý.

**Điền bằng mean**

Ví dụ:
```
mean_score = df["Score"].mean()

df["Score"] = df["Score"].fillna(
    mean_score
)
```
Nếu Score:
```
8.5
NaN
9.0
6.0
8.0
```
mean được tính từ các giá trị không missing.

Sau đó NaN được thay bằng mean.

**Điền String**

Ví dụ:
```
df["City"] = df["City"].fillna("Unknown)
```
Đây thường dùng cho categorical data

**Khi nào dropna, khi nào fillna?**

Ta chỉ cần hiểu:
```
dropna()
→ loại bỏ dữ liệu bị thiếu

fillna()
→ giữ row lại nhưng thay giá trị thiếu
```

Việc chọn cái nào phụ thuộc dataset và bài toán

# **Task 2 — Duplicate Data**

In [51]:
# Dataset

data = {
    "Name": ["An", "Binh", "Cuong", "An"],
    "Score": [8.5, 7.0, 9.0, 8.5]
}

df = pd.DataFrame(data)

# Row của An bị lặp

**duplicated()**

```
df.duplicated()
```
Output có thể:

```
0    False
1    False
2    False
3    True
```
Row thứ 4 trùng row đầu

**Đếm duplicate**

In [52]:
df.duplicated().sum()
# -> 1

np.int64(1)

**Xóa duplicate**

In [53]:
df.drop_duplicates()

    Name  Score
0     An    8.5
1   Binh    7.0
2  Cuong    9.0

**Duplicate theo một column**

Ví dụ:
```
df.duplicated(subset=["Name"])
```
Nó chỉ xét column Name

Tương tự:
```
df.drop_duplicates(subset=["Name"])
```

**keep**

Pandas mặc định:
```
df.drop_duplicate(keep="first")
```

nghĩa là:

`giữ row đầu tiên, xóa duplicate sau đó.`

Optional hôm nay:
```
keep="last"
```
-> giữ row cuối

# **Task 3 — Filtering**

In [54]:
data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa"],
    "Age": [22, 25, 21, 23, 24],
    "Score": [8.5, 7.0, 9.0, 6.0, 8.0],
    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi"]
}

df = pd.DataFrame(data)

# Filter Score >= 8
# df["Score"] >= 8

# Giống NumPy Boolean Indexing mà ta đã học
df[df["Score"] >= 8]

    Name  Age  Score   City
0     An   22    8.5  Hanoi
2  Cuong   21    9.0  Hanoi
4    Hoa   24    8.0  Hanoi

**Tư duy filtering**
```
df["Score"] >= 8
        ↓
Boolean Series
        ↓
df[Boolean Series]
        ↓
chỉ lấy rows True
```

Đây chính là Boolean Indexing phiên bản Pandas

In [55]:
# Filter String

df[df["City"] == "Hanoi"]
# chỉ students ở Hanoi

    Name  Age  Score   City
0     An   22    8.5  Hanoi
2  Cuong   21    9.0  Hanoi
4    Hoa   24    8.0  Hanoi

In [56]:
# Filter khác

df[df["City"] != "Hanoi"]
# chỉ students không ở Hanoi

   Name  Age  Score    City
1  Binh   25    7.0     HCM
3  Dung   23    6.0  Danang

In [57]:
# Filter khoảng

df[df["Age"] > 22]

   Name  Age  Score    City
1  Binh   25    7.0     HCM
3  Dung   23    6.0  Danang
4   Hoa   24    8.0   Hanoi

# **Task 4 — Multiple Conditions**

**AND**

Muốn
```
Score >= 8
AND
City == Hanoi
```
Dùng:
```
df[
    (df["Score"] >= 8)
    &
    (df["City"] == "Hanoi")
]
```

In [58]:
# OR
df[(df["Score"] >= 9) | (df["City"] == "HCM")]

#  NOT
df[~(df["City"] == "Hanoi")]

# nhưng để dễ đọc hơn, có thể dùng:
df[df["City"] != "Hanoi"]

   Name  Age  Score    City
1  Binh   25    7.0     HCM
3  Dung   23    6.0  Danang

**Rất quan trọng: Pandas không dùng and / or**

Sai:
```
(df["Score"] >= 8)
and
(df["City"] == "Hanoi")
```
Đúng:
```
& → AND
| → OR
~ → NOT
```
Vì chúng ta đang làm việc với Series boolean, không phải một boolean duy nhất

In [59]:
# Filter và chọn columns cùng lúc
high_scores = df[df["Score"] >= 8]

print(high_scores[["Name", "Score"]])

    Name  Score
0     An    8.5
2  Cuong    9.0
4    Hoa    8.0

# **Task 5 — Sorting**

In [60]:
# Sắp xếp tăng dần
df.sort_values(by = "Score")

    Name  Age  Score    City
3   Dung   23    6.0  Danang
1   Binh   25    7.0     HCM
4    Hoa   24    8.0   Hanoi
0     An   22    8.5   Hanoi
2  Cuong   21    9.0   Hanoi

In [61]:
# Sắp xếp giảm dần
df.sort_values(by = "Score", ascending=False)

    Name  Age  Score    City
2  Cuong   21    9.0   Hanoi
0     An   22    8.5   Hanoi
4    Hoa   24    8.0   Hanoi
1   Binh   25    7.0     HCM
3   Dung   23    6.0  Danang

In [62]:
# Sort theo nhiều columns

df.sort_values(by = ["City", "Score"])

    Name  Age  Score    City
3   Dung   23    6.0  Danang
1   Binh   25    7.0     HCM
4    Hoa   24    8.0   Hanoi
0     An   22    8.5   Hanoi
2  Cuong   21    9.0   Hanoi

In [63]:
# Mỗi column một direction

df.sort_values(by = ["City", "Score"], ascending=[True, False])

    Name  Age  Score    City
3   Dung   23    6.0  Danang
1   Binh   25    7.0     HCM
2  Cuong   21    9.0   Hanoi
0     An   22    8.5   Hanoi
4    Hoa   24    8.0   Hanoi

In [64]:
# sort_index()
df.sort_index()

    Name  Age  Score    City
0     An   22    8.5   Hanoi
1   Binh   25    7.0     HCM
2  Cuong   21    9.0   Hanoi
3   Dung   23    6.0  Danang
4    Hoa   24    8.0   Hanoi

**Một workflow Data Cleaning đơn giản**

In [65]:
# df = pd.read_csv("students.csv")

# print(df.isna().sum())

# print(df.duplicated().sum())

# df["Score"] = df["Score"].fillna(df["Score"].mean())

# df = df.drop_duplicates()

# high_scores = df[df["Score"] >= 8]

# high_scores = high_scores.sort_values(by = "Score", ascending=False)

Ta có thể thấy:
```
Load
↓
Check missing
↓
Fix missing
↓
Remove duplicates
↓
Filter
↓
Sort
```

# **Task 6 — Coding Practice**

In [99]:
# Dataset

import pandas as pd
import numpy as np

data = {
    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy", "An"],

    "Age": [22, 25, np.nan, 23, 24, 26, 22],

    "Score": [8.5, np.nan, 9.0, 6.0, 8.0, 7.5, 8.5],

    "City": ["Hanoi", "HCM", "Hanoi", "Danang", "Hanoi", None, "Hanoi"]
}

df = pd.DataFrame(data)

In [100]:
# Ex 1: Ex 1 — Check Missing
df.isna()

    Name    Age  Score   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False   True
6  False  False  False  False

In [101]:
# Ex 2: Count Missing
df.isna().sum()

Name     0
Age      1
Score    1
City     1
dtype: int64

In [104]:
# Ex 3: Missing Score
# Lấy những rows có Score missing
print(df[df["Score"].isna()])

   Name   Age  Score City
1  Binh  25.0    NaN  HCM

In [105]:
# Ex 4: Non-Missing Score
df[df["Score"].notna()]

    Name   Age  Score    City
0     An  22.0    8.5   Hanoi
2  Cuong   NaN    9.0   Hanoi
3   Dung  23.0    6.0  Danang
4    Hoa  24.0    8.0   Hanoi
5    Huy  26.0    7.5    None
6     An  22.0    8.5   Hanoi

In [71]:
# Ex 5: Fill Score
mean_score = df["Score"].mean()

df["Score"] = df["Score"].fillna(mean_score)

print(df)

    Name   Age     Score    City
0     An  22.0  8.500000   Hanoi
1   Binh  25.0  7.916667     HCM
2  Cuong   NaN  9.000000   Hanoi
3   Dung  23.0  6.000000  Danang
4    Hoa  24.0  8.000000   Hanoi
5    Huy  26.0  7.500000    None
6     An  22.0  8.500000   Hanoi

In [72]:
# Ex 6: Fill City
df["City"] = df["City"].fillna("Unknown")

print(df)

    Name   Age     Score     City
0     An  22.0  8.500000    Hanoi
1   Binh  25.0  7.916667      HCM
2  Cuong   NaN  9.000000    Hanoi
3   Dung  23.0  6.000000   Danang
4    Hoa  24.0  8.000000    Hanoi
5    Huy  26.0  7.500000  Unknown
6     An  22.0  8.500000    Hanoi

In [106]:
# Ex 7: Check Duplicates
print(df.duplicated())
print(df.duplicated().sum())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
1

In [107]:
# Ex 8: Remove Duplicates
df = df.drop_duplicates()
print(df.duplicated().sum())

0

In [75]:
# Ex 9: Filter Score
df[df["Score"] >= 8]

    Name   Age  Score   City
0     An  22.0    8.5  Hanoi
2  Cuong   NaN    9.0  Hanoi
4    Hoa  24.0    8.0  Hanoi
6     An  22.0    8.5  Hanoi

In [76]:
# Ex 10: Filter City
df[df["City"] == "Hanoi"]

    Name   Age  Score   City
0     An  22.0    8.5  Hanoi
2  Cuong   NaN    9.0  Hanoi
4    Hoa  24.0    8.0  Hanoi
6     An  22.0    8.5  Hanoi

In [77]:
# Ex 11: Multiple Conditions
df[(df["Score"] >= 8) & (df["City"] == "Hanoi")]

    Name   Age  Score   City
0     An  22.0    8.5  Hanoi
2  Cuong   NaN    9.0  Hanoi
4    Hoa  24.0    8.0  Hanoi
6     An  22.0    8.5  Hanoi

In [78]:
# Ex 12: OR Condition
df[(df["Score"] >= 9) | (df["Age"] >= 25)]

    Name   Age     Score     City
1   Binh  25.0  7.916667      HCM
2  Cuong   NaN  9.000000    Hanoi
5    Huy  26.0  7.500000  Unknown

In [79]:
# Ex 13: Sort Score Ascending
df.sort_values(by = "Score")

    Name   Age     Score     City
3   Dung  23.0  6.000000   Danang
5    Huy  26.0  7.500000  Unknown
1   Binh  25.0  7.916667      HCM
4    Hoa  24.0  8.000000    Hanoi
6     An  22.0  8.500000    Hanoi
0     An  22.0  8.500000    Hanoi
2  Cuong   NaN  9.000000    Hanoi

In [80]:
#  Ex 14: Sort Score Descending
df.sort_values(by = "Score", ascending=False)

    Name   Age     Score     City
2  Cuong   NaN  9.000000    Hanoi
0     An  22.0  8.500000    Hanoi
6     An  22.0  8.500000    Hanoi
4    Hoa  24.0  8.000000    Hanoi
1   Binh  25.0  7.916667      HCM
5    Huy  26.0  7.500000  Unknown
3   Dung  23.0  6.000000   Danang

In [81]:
#  Ex 15: Filter + Sort
high_scores = df[df["Score"] >= 7]

high_scores = high_scores.sort_values(by = "Score", ascending=False)

print(high_scores[["Name", "Score", "City"]])

    Name     Score     City
2  Cuong  9.000000    Hanoi
0     An  8.500000    Hanoi
6     An  8.500000    Hanoi
4    Hoa  8.000000    Hanoi
1   Binh  7.916667      HCM
5    Huy  7.500000  Unknown

# **Task 7 — Mini Challenge**
# **Student Data Cleaning Pipeline**

In [82]:
# Dataset

import pandas as pd
import numpy as np

data = {
    "StudentID": [101, 102, 103, 104, 105, 106, 102],

    "Name": ["An", "Binh", "Cuong", "Dung", "Hoa", "Huy", "Binh"],

    "Age": [22, 25, 21, np.nan, 24, 26, 25],

    "Math": [8.5, 6.0, 9.0, 5.5, np.nan, 8.0, 6.0],

    "English": [7.0, 8.0, 9.5, 6.0, 8.5, np.nan, 8.0],

    "AI": [9.0, 7.5, 8.5, 7.0, 8.0, 9.5, 7.5],

    "City": ["Hanoi", "HCM", "Hanoi", "Danang", None, "HCM", "HCM"]
}

df = pd.DataFrame(data)

In [108]:
# Require 1: Overview
print(df.head())

print(df.shape)

df.info()

    Name   Age  Score    City
0     An  22.0    8.5   Hanoi
1   Binh  25.0    NaN     HCM
2  Cuong   NaN    9.0   Hanoi
3   Dung  23.0    6.0  Danang
4    Hoa  24.0    8.0   Hanoi
(6, 4)
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     5 non-null      float64
 2   Score   5 non-null      float64
 3   City    5 non-null      object
dtypes: float64(2), object(2)
memory usage: 240.0+ bytes

In [84]:
# Require 2: Missing Values
print(df.isna().sum())

StudentID    0
Name         0
Age          1
Math         1
English      1
AI           0
City         1
dtype: int64

In [85]:
# Require 3: Fill Numeric Missing
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Math"] = df["Math"].fillna(df["Math"].mean())
df["English"] = df["English"].fillna(df["English"].mean())

print(df)

   StudentID   Name        Age      Math   English   AI    City
0        101     An  22.000000  8.500000  7.000000  9.0   Hanoi
1        102   Binh  25.000000  6.000000  8.000000  7.5     HCM
2        103  Cuong  21.000000  9.000000  9.500000  8.5   Hanoi
3        104   Dung  23.833333  5.500000  6.000000  7.0  Danang
4        105    Hoa  24.000000  7.166667  8.500000  8.0    None
5        106    Huy  26.000000  8.000000  7.833333  9.5     HCM
6        102   Binh  25.000000  6.000000  8.000000  7.5     HCM

In [86]:
# Require 4: Fill City
df["City"] = df["City"].fillna("Unknown")

print(df)

   StudentID   Name        Age      Math   English   AI     City
0        101     An  22.000000  8.500000  7.000000  9.0    Hanoi
1        102   Binh  25.000000  6.000000  8.000000  7.5      HCM
2        103  Cuong  21.000000  9.000000  9.500000  8.5    Hanoi
3        104   Dung  23.833333  5.500000  6.000000  7.0   Danang
4        105    Hoa  24.000000  7.166667  8.500000  8.0  Unknown
5        106    Huy  26.000000  8.000000  7.833333  9.5      HCM
6        102   Binh  25.000000  6.000000  8.000000  7.5      HCM

In [87]:
# Require 5: Verify Missing
print(df.isna().sum())

StudentID    0
Name         0
Age          0
Math         0
English      0
AI           0
City         0
dtype: int64

In [88]:
# Require 6: Detect Duplicate
print(df.duplicated().sum())

1

In [89]:
# Require 7: Remove Duplicate
df = df.drop_duplicates()

print(df)

   StudentID   Name        Age      Math   English   AI     City
0        101     An  22.000000  8.500000  7.000000  9.0    Hanoi
1        102   Binh  25.000000  6.000000  8.000000  7.5      HCM
2        103  Cuong  21.000000  9.000000  9.500000  8.5    Hanoi
3        104   Dung  23.833333  5.500000  6.000000  7.0   Danang
4        105    Hoa  24.000000  7.166667  8.500000  8.0  Unknown
5        106    Huy  26.000000  8.000000  7.833333  9.5      HCM

In [90]:
# Require 8: High Performers

high_performers = df[df["AI"] >= 8]
print(high_performers[["Name", "AI"]])

    Name   AI
0     An  9.0
2  Cuong  8.5
4    Hoa  8.0
5    Huy  9.5

In [91]:
# Require 9: Hanoi Students
print(df[df["City"] == "Hanoi"])

   StudentID   Name   Age  Math  English   AI   City
0        101     An  22.0   8.5      7.0  9.0  Hanoi
2        103  Cuong  21.0   9.0      9.5  8.5  Hanoi

In [92]:
# Require 10: Strong Students
strong_students = df[(df["Math"] >= 8) & (df["AI"] >= 8)]

print(strong_students[["Name", "Math", "AI"]])

    Name  Math   AI
0     An   8.5  9.0
2  Cuong   9.0  8.5
5    Huy   8.0  9.5

In [93]:
# Require 11: Multiple Criteria
result = df[(df["English"] >= 8) | (df["AI"] >= 9)]

print(result)

   StudentID   Name   Age      Math   English   AI     City
0        101     An  22.0  8.500000  7.000000  9.0    Hanoi
1        102   Binh  25.0  6.000000  8.000000  7.5      HCM
2        103  Cuong  21.0  9.000000  9.500000  8.5    Hanoi
4        105    Hoa  24.0  7.166667  8.500000  8.0  Unknown
5        106    Huy  26.0  8.000000  7.833333  9.5      HCM

In [94]:
# Require 12: Sort AI
print(df.sort_values(by = "AI", ascending=False))

   StudentID   Name        Age      Math   English   AI     City
5        106    Huy  26.000000  8.000000  7.833333  9.5      HCM
0        101     An  22.000000  8.500000  7.000000  9.0    Hanoi
2        103  Cuong  21.000000  9.000000  9.500000  8.5    Hanoi
4        105    Hoa  24.000000  7.166667  8.500000  8.0  Unknown
1        102   Binh  25.000000  6.000000  8.000000  7.5      HCM
3        104   Dung  23.833333  5.500000  6.000000  7.0   Danang

In [95]:
# Require 13: Sort Math
print(df.sort_values(by = "Math"))

   StudentID   Name        Age      Math   English   AI     City
3        104   Dung  23.833333  5.500000  6.000000  7.0   Danang
1        102   Binh  25.000000  6.000000  8.000000  7.5      HCM
4        105    Hoa  24.000000  7.166667  8.500000  8.0  Unknown
5        106    Huy  26.000000  8.000000  7.833333  9.5      HCM
0        101     An  22.000000  8.500000  7.000000  9.0    Hanoi
2        103  Cuong  21.000000  9.000000  9.500000  8.5    Hanoi

In [96]:
# Require 14: Clean Final Dataset
final_df = df[["StudentID", "Name", "Math", "English", "AI", "City"]]

final_df = final_df.sort_values(by = "AI", ascending=False)
print(final_df)

   StudentID   Name      Math   English   AI     City
5        106    Huy  8.000000  7.833333  9.5      HCM
0        101     An  8.500000  7.000000  9.0    Hanoi
2        103  Cuong  9.000000  9.500000  8.5    Hanoi
4        105    Hoa  7.166667  8.500000  8.0  Unknown
1        102   Binh  6.000000  8.000000  7.5      HCM
3        104   Dung  5.500000  6.000000  7.0   Danang

In [97]:
# Require 15: Save Clean Data
final_df.to_csv("clean_students.csv", index=False)

print(pd.read_csv("clean_students.csv"))

   StudentID   Name      Math   English   AI     City
0        106    Huy  8.000000  7.833333  9.5      HCM
1        101     An  8.500000  7.000000  9.0    Hanoi
2        103  Cuong  9.000000  9.500000  8.5    Hanoi
3        105    Hoa  7.166667  8.500000  8.0  Unknown
4        102   Binh  6.000000  8.000000  7.5      HCM
5        104   Dung  5.500000  6.000000  7.0   Danang